### ISSUE TITLE
When downloading latest binaries from 3.0.0... actual linux binary is version 2.2.61

### ISSUE THREAD

**Issue by tehkuhnz** [pivotalservices/cfops#101]
I suspect there is a packaging issue with the cfops binaries ( I would expect to see version 3.0.0 )

NAME:
   cfops - Cloud Foundry Operations Tool
USAGE:
   cfops  command [command options] [arguments...]
   
VERSION:
   v2.2.61

**Comment by kdudala1** [comment]
Thanks @tehkuhnz . Fixed in 3.0.1.
