### ISSUE TITLE
Not able to take backup using cfops

### ISSUE THREAD

**Issue by ReenaAcharya** [pivotalservices/cfops#102]
Hi,

I am trying to take backup of ops-manager and elastic runtime using cfops but I am getting following error when I execute cfops commands:-
error in save http request {"error":"Your UAA access token has expired and Your UAA access token does not have either \"opsman.admin\" or \"opsman.user\" scope"}
falling back to basic auth for legacy system {"error":"unauthorized","error_description":"No available authentication providers."}

I am using cfops v2.2.29.

Any solution on this will be very helpful.
Thanks.

**Comment by kdudala1** [comment]
Hi,

Thank you for your note.

Here are a few steps to help you resolve the issue:

1) Visit cfops.io and download the latest release of cfops

2) Take a look at the troubleshooting section on cfops.io, in particular
the authentication section, and try the remediations described there

3) If you're still unable to resolve the issue, please file a support
ticket at support.pivotal.io

Thanks,
The PCF Data Protection team
