### ISSUE TITLE
cfops 3.0.2 on 1.8 PCF use the wrong version of pg_dump and gets an empty file

### ISSUE THREAD

**Issue by snorkmitzumi** [pivotalservices/cfops#107]
On PCF 1.8 we are trying to create pg_dump and getting the following error:
```2017/02/20 19:03:54 D0220 19:03:54.912244 6216 pgdump.go:67] pgdump Dump called:  PGPASSWORD=redacted /var/vcap/packages/postgres-9.4.2/bin/pg_dump -Fc -h localhost -U admin -p 2544 ccdb Process exited with status 127```

 https://github.com/pivotalservices/cfbackup/blob/24227a9766d0e43b8bc43e80678dadd9c69991c7/installation_settings.go makes it look like 1.8 isn't in the maps of the `cfbackup` portion that I am _assuming_ is in the tool

Can it be fixed to match PG 9.4.6 version?

**Comment by keviningvalson** [comment]
Debug message produced

`2017/02/20 19:03:54 D0220 19:03:54.912244 6216 pgdump.go:67] pgdump Dump called:  PGPASSWORD=redacted /var/vcap/packages/postgres-9.4.2/bin/pg_dump -Fc -h localhost -U admin -p 2544 ccdb Process exited with status 127`

for the ccdb

```
$ pwd
/var/vcap/packages
bosh_r8i8cd8dd@57eb6387-f2aa-4964-8745-48202bafe9f6:/var/vcap/packages$ ls
loggregator_common  metron_agent  postgres-9.4.6  postgres-common
```

**Comment by lsilvapvt** [comment]
Pull Request (#47)[https://github.com/pivotalservices/cfbackup/pull/47] submitted to cfbackup repo in order to fix this problem.

**Comment by lsilvapvt** [comment]
A beta version of the CFOps tool containing the PR 47 mentioned above has been provided by the CFOps engineers and then successfully tested by the affected customer. Customer is now waiting for official CFOps release which contains the fix.

**Comment by lsilvapvt** [comment]
Official release issued to incorporate the provided fix: https://github.com/pivotalservices/cfops/releases/tag/v3.0.8
