### ISSUE TITLE
ERT using cfops version v3.1.2 fails; OpsMgr passes

### ISSUE THREAD

**Issue by findneville** [pivotalservices/cfops#114]
While performing CF Backups, the ERT backup fails. Backing up OpsMgr passes without any issues. I tried checking the validity of the uaac client and it is working fine. If it wasnt working, OpsMgr backups would fail too. 

Outputs
============

CFOPS Version
]# /usr/local/bin/cfops3.1.12 version
cfops version v3.1.2

UAAC Client 
========
]# /opt/comcast/ruby/2.1.2/bin/uaac context                                                             
[0]*[https://myOMFQDN/uaa]
  skip_ssl_validation: true

  [0]*[backupuser]
      client_id: backupuser
      access_token: backupusertoken
      token_type: bearer
      expires_in: 43199
      scope: opsman.admin
      jti: backupuserjti

DEBUG OUTPUT OF COMMAND
=====================
LOG_LEVEL=debug /usr/local/bin/cfops3.1.12 backup --opsmanagerhost myOMFQDN --clientid backupuser --clientsecret backuppwd --opsmanageruser omuser -d /file/path --tile elastic-runtime -nfs bp

2017/07/17 10:58:24 D0717 10:58:24.8856 16863 init.go:38] not loading plugins: %!(EXTRA *os.PathError=open ./plugins: no such file or directory, []os.FileInfo=[])
2017/07/17 10:58:24 D0717 10:58:24.885991 16863 createCliCommand.go:85] checking registry for 'elastic-runtime' tile
2017/07/17 10:58:24 D0717 10:58:24.886025 16863 createCliCommand.go:88] found tile in registry
2017/07/17 10:58:24 D0717 10:58:24.886065 16863 createCliCommand.go:91] we have all required flags and a proper builder
2017/07/17 10:58:24 D0717 10:58:24.886521 16863 remote_execute.go:26] using password for authn
2017/07/17 10:58:24 D0717 10:58:24.886599 16863 opsmanager.go:90] Exporting url 'https://myOMFQDN/api/installation_settings'
2017/07/17 10:58:24 D0717 10:58:24.886631 16863 opsmanager.go:144] attempting to auth against%!(EXTRA string=https://myOMFQDN/api/installation_settings)
2017/07/17 10:58:24 D0717 10:58:24.88667 16863 opsmanager.go:196] aquiring your token from: %!(EXTRA *url.URL=https://myOMFQDN/api/installation_settings, string=https://myOMFQDN/api/installation_settings)
2017/07/17 10:58:25 D0717 10:58:25.191005 16863 opsmanager.go:202] token acquired
2017/07/17 10:58:26 D0717 10:58:26.74029 16863 createCliCommand.go:74] Running backup for tile: struct { tileregistry.Tile; tileregistry.Closer }{Tile:(*elasticruntime.ElasticRuntime)(0xc4200aa000), Closer:(*elasticruntime.TempFile)(0xc42000e060)}
2017/07/17 10:58:26 E0717 10:58:26.987062 16863 createCliCommand.go:52] there was an error: failed on check for valid director credentials: failed creating new director: failed creating bosh client: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"unauthorized","error_description":"No available authentication providers."} running backup on elastic-runtime tile:tile

**Comment by Murryy79** [comment]
@findneville did you resolve this issue? 
thanks

**Comment by henryaj** [comment]
Hi, I'm closing this out in favour of resolving on Pivotal Support. Thanks.
