### ISSUE TITLE
pcf 2.x support?

### ISSUE THREAD

**Issue by a-nanasov** [pivotalservices/cfops#118]
Hi, documentation says "CF OPS is currently compatible with PCF 1.6, 1.7, 1.8, 1.9 and 1.10 installations on vSphere, Openstack, and Amazon Web Services.", is this still true? Is 2.x pcf support planned?

Thank you.

**Comment by sneal** [comment]
For newer PCF versions you'll need to use [BBR](https://docs.pivotal.io/pivotalcf/2-0/customizing/backup-restore/backup-pcf-bbr.html)
