### ISSUE TITLE
Elastic Runtime tile backup failing with "invalid or incomplete system info object" error

### ISSUE THREAD

**Issue by mdcarlson** [pivotalservices/cfops#34]
I can successfully backup OpsManager tile against both 1.4.2 and 1.5.0.  In both cases, the backup of the ElasticRuntime tile fails with a "invalid or incomplete system info object" error message.

See gist: https://gist.github.com/mdcarlson/9d2c7e76ba611e1f7483 for log output.

We continue to troubleshoot to rule out config-related issues, but I wanted to share this error in case others have seen it.

**Comment by sjhutto** [comment]
Unable to reproduce after successfully updating OpsMan tile to 1.5 and restarting, backup now appears to be backing up both the database and ElasticRuntime.

**Comment by xchapter7x** [comment]
Also, please try using our latest release binaries here (https://github.com/pivotalservices/cfops/releases/tag/v1.0.0)

Before this release we were not officially 1.5 compatible for ER and OpsManager.
