### ISSUE TITLE
SSH Exception when running cfops with OpsManager 1.5.5

### ISSUE THREAD

**Issue by jigsheth57** [pivotalservices/cfops#37]
./cfops --logLevel "debug" b --opsmanagerhost opshostIP --adminuser admin --adminpass webapppassword --opsmanageruser ubuntu --opsmanagerpass password -d /tmp

ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**Comment by xchapter7x** [comment]
sorry for the slow response.
can you please both run:
```
$ cfops version
```
and
```
$ LOG_LEVEL=debug cfops backup ...
```

it will provide useful information to be able to help debug your issue. However, that error seems like it is either, using a old version of `cfops` or you are running it from a machine which does not have access to the network where the Elastic Runtime VMs are running.

**Comment by jigsheth57** [comment]
Turned out that error was caused by the ‘$’ in password. Once the ‘$’ was escape with single quote, it worked.

Best Regards,
Jignesh Sheth | Sr. Platform Architect | Pivotal
Phone: (847)970-0298 | jigsheth@pivotal.io <mailto:jigsheth@pivotal.io>





Platform as a Service | Agile Development | Big Data
www.Pivotal.io <http://www.pivotal.io/> | http://pivotal.io/cloud-native <http://pivotal.io/cloud-native>
