### ISSUE TITLE
Backup MySQL Tile

### ISSUE THREAD

**Issue by mcintyred** [pivotalservices/cfops#41]
Please can you add the ability to back up the MySQL tile. This is used by a variety of other services such as Mobile Push, Spring Cloud Services etc, so being able to back it up to the filesystem is really needed.

I understand that the tile itself can backup to S3, but S3 is not available in all environments.

**Comment by calebwashburn** [comment]
@mcintyred - See plugin support added to cfops (http://www.cfops.io/) as there are now plugins to backup mysql, redis, rabbit-mq.  If there are missing capabilities submit a feature request.
