### ISSUE TITLE
Unimplemented flags

### ISSUE THREAD

**Issue by mcintyred** [pivotalservices/cfops#45]
These flags don't seem to work:  -logLevel, --version and -v

**Comment by xchapter7x** [comment]
correct, those have been removed in favor of
`cfops version`
&
`LOG_LEVEL=(debug|info|error|etc) cfops ...`

we will remove the unimplemented flags in a coming release. thanks for calling this out.

**Comment by xchapter7x** [comment]
this is fixed as of commit:
https://github.com/pivotalservices/cfops/commit/5c01ef432cd07d1334dcf32f11cda837a6fc6c0c. 

should appear in a release shortly. marking closed for now.
