### ISSUE TITLE
Documentation - what does a tile mean to cfops?

### ISSUE THREAD

**Issue by mcintyred** [pivotalservices/cfops#47]
The way the word "tile" is used in the docs is a bit confusing. If I run "cfops backup -t ops-manager" I would expect to get a backup of the OpsManager Director tile settings, and associated base assets such as stemcells.

-t elastic-runtime would save ER tile settings, databases etc
-t rabbitmq would save RabbitMQ tile settings and persistent messages.

etc.

As it is "-t opsmanager" really means "All foundation tiles and their configuration, but not any persistent data", and "-t &lt;tilename&gt;" means "save the persistent data of tile &lt;tilename&gt;".

**Comment by xchapter7x** [comment]
in cfops a `tile` is something which can be both backed up and restored. 

The `ops-manager` backup will backup the state of a given ops manager. This means run a full export of the ops manager (configs, releases) as well as grab the deployment manifests from the ops manager director.

The `elastic-runtime` backup will backup the state of a given elastic runtime. This means (consoledb, ccdb, uaadb, mysqldb, nfs)

I hope this offers some clarity. Feel free to chat more with us in the gitter channel if you like. 

closing this issue for now.
