### ISSUE TITLE
cfops panic message

### ISSUE THREAD

**Issue by awstaples** [pivotalservices/cfops#51]
Received panic message while using cfops to backup the elastic runtime tile.   There was quite a bit of output from cfops after this.  Is this a failure, or just informational?
cfops version v2.0.49

---snip
we have a cf product
we have some psql
we have some psql
we have some psql
2016/01/28 10:37:31 I0128 10:37:31.22895 8786 elasticruntime.go:138] Exporting nfs_server
^[[B2016/01/28 10:41:05 I0128 10:41:05.337621 8786 elasticruntime.go:138] Exporting consoledb
2016/01/28 10:41:05 I0128 10:41:05.515441 8786 elasticruntime.go:138] Exporting ccdb
2016/01/28 10:41:05 I0128 10:41:05.75453 8786 elasticruntime.go:138] Exporting uaadb
2016/01/28 10:41:05 I0128 10:41:05.868943 8786 elasticruntime.go:138] Exporting mysql
panic: you have to extend SystemInfo and implement GetPersistanceBackup method on the child
---snip

**Comment by xchapter7x** [comment]
what is the command you ran?
can you confirm you set the ER_VERSION=1.6 env var

also, if you have set the LOG_LEVEL=debug this is normal output not a stack trace

**Comment by awstaples** [comment]
Here is the cmd I am running: 
ER_VERSION=1.6 ./cfops backup --omh <ip of opsmgr> --du <cfadmin> --dp <passwd> --omu ubuntu --omp <passwd> -d /opt/cfops/techlab -t elastic-runtime

**Comment by awstaples** [comment]
Output from the cmd is large without debug.  With debug enabled it is, as expected, much larger! 
What specific sections are needed?.  
The only item in the target folder when the cmd stops is mysql.backup

**Comment by xchapter7x** [comment]
If your elastic runtime is 1.6 and configured for MySQL persistence, then
you should see a mysql.backup and a nfs.backup .

If you are not setting debug output then the output should be minimal,
provided there are no errors.

Can you pull out any actual errors and paste them here. Likely something
regarding NFS.

Also, how big is that mysql.backup? Is it a complete dump or is that where
the error happened?

Let me know.

-John
