### ISSUE TITLE
Auto Detect the version of Elastic Runtime and OpsManager Tiles 

### ISSUE THREAD

**Issue by kelapure** [pivotalservices/cfops#57]
When running cfops backup and restore to a PCF 1.6 environment it is critical that the operator sets the `ER_VERSION=1.6` environment variable otherwise the following error is seen

```
$ cfops restore -d /staging/pcf-swdctest0224/ --tile elastic-runtime
2016/02/26 09:58:29 E0226 09:58:29.835868 20849 createCliCommand.go:42] there was an error: invalid director credentials running restore on elastic-runtime tile:&{{/staging/pcf-swdctest0224/ false 0xc820428620} /tmp/installation.json366910325 {map[MysqldbInfo:0xc8202375c0 DirectorInfo:0xc820440000 NfsInfo:0xc8204400b0]} [0xc8204400b0 0xc8202375c0] <nil> cf-5221d796caae9224f717 }
```
This is easy to forget. Can cfops auto detect the target PCF environment eliminating the need to set this ER_VERSION env variable. 

I believe this will be a major usability enhancement and improve first time user experience.

**Comment by xchapter7x** [comment]
latest version supports this feature
