### ISSUE TITLE
CfOps restore of Ops Manager on OpenStack

### ISSUE THREAD

**Issue by pakiheart** [pivotalservices/cfops#59]
When trying to use the tool for Ops Manager restore it fails at the end but the restore is successful. We discovered this during Ops Manager upgrade

Steps to Reproduce:
1) backup Ops Manager using cfops tool
2) deployed latest version of Ops Manager
3) ran restore using the tool and got the following error:
2016/03/17 18:50:36 D0317 18:50:36.775838 19556 createCliCommand.go:74] checking registry for 'ops-manager' tile
2016/03/17 18:50:36 D0317 18:50:36.775894 19556 createCliCommand.go:77] found tile in registry
2016/03/17 18:50:36 D0317 18:50:36.775912 19556 createCliCommand.go:80] we have all required flags and a proper builder
2016/03/17 18:50:36 D0317 18:50:36.77596 19556 remote_execute.go:25] using password for authn
2016/03/17 18:50:36 D0317 18:50:36.775988 19556 opsmanager.go:74] Exporting url 'https://10.81.215.8/api/installation_settings'
2016/03/17 18:50:36 D0317 18:50:36.776019 19556 opsmanager.go:128] attempting to auth against%!(EXTRA string=https://10.81.215.8/api/installation_settings)
2016/03/17 18:50:36 D0317 18:50:36.77604 19556 opsmanager.go:169] aquiring your token from: %!(EXTRA _url.URL=https://10.81.215.8/api/installation_settings, string=https://10.81.215.8/api/installation_settings)
2016/03/17 18:50:36 I0317 18:50:36.808296 19556 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/03/17 18:50:37 D0317 18:50:37.205572 19556 opsmanager.go:158] called basic auth on legacy ops manager%!(EXTRA string=https://10.81.215.8/api/installation_settings, <nil>)
2016/03/17 18:50:37 D0317 18:50:37.210333 19556 opsmanager_builder.go:18] we found a iaas info block
..................
2016/03/17 18:52:16 D0317 18:52:16.02697 19556 opsmanager.go:229] Request for https://10.81.215.8/api/installation_asset_collection succeeded with status: 200 OK
2016/03/17 18:52:16 D0317 18:52:16.027101 19556 opsmanager.go:194] removing deployment files
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x616276]
goroutine 1 [running]:
panic(0x99e080, 0xc82000e0c0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/pivotalservices/gtils/command.(_DefaultRemoteExecutor).Execute(0xc820318060, 0x7f963a9e53d8, 0xc82033a700, 0xc8203166e0, 0x9c, 0x0, 0x0)
    /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/gtils/command/remote_execute.go:94 +0x86
github.com/pivotalservices/cfbackup/tiles/opsmanager.(_OpsManager).removeExistingDeploymentFiles(0xc8200dfb00, 0x0, 0x0)
    /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:245 +0x257
github.com/pivotalservices/cfbackup/tiles/opsmanager.(_OpsManager).importInstallation.func1(0xc820320e58, 0xc8200dfb00)
    /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:195 +0x69
github.com/pivotalservices/cfbackup/tiles/opsmanager.(_OpsManager).importInstallation(0xc8200dfb00, 0x0, 0x0)
    /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:201 +0x2dc
github.com/pivotalservices/cfbackup/tiles/opsmanager.(_OpsManager).Restore(0xc8200dfb00, 0x0, 0x0)
    /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:187 +0x2f
main.runTileAction(0xa5deb0, 0x7, 0x7f963a9ebce0, 0xc8200dfb00, 0x0, 0x0)
    /go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:68 +0x244
main.buraAction.func1(0xc8200df680)
    /go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:41 +0x88c
github.com/codegangsta/cli.Command.Run(0xa5deb0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb1a040, 0x2b, 0xc82007f7c0, ...)
    /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:163 +0x131f
github.com/codegangsta/cli.(*App).Run(0xc8200df440, 0xc82000a0e0, 0xe, 0xe, 0x0, 0x0)
    /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:179 +0x1164
main.main()
    /go/src/github.com/pivotalservices/cfops/cmd/cfops/main.go:26 +0x6f

NOTE: Restore does work because all the tiles are in place with their proper configuration

**Comment by xchapter7x** [comment]
can you please provide:
- cfops version
- cfops command executed

thanks.

**Comment by pakiheart** [comment]
cfops version - v2.1.1
cf restore ..... -t ops-manager

**Comment by henryaj** [comment]
Looks like this is inactive, so closing for now. If the OP is still having problems, please contact [Pivotal Support](support.pivotal.io).
