### ISSUE TITLE
cfops should not remove bosh-deployments.yml by default

### ISSUE THREAD

**Issue by mkuratczyk** [pivotalservices/cfops#61]
Hi. cfops restore removes the bosh-deployments.yml file by default to ensure a fresh state. This causes problems if cfops restore is used to load settings into a new Ops Manager during upgrade. The import succeeds and OpsManager shows all the tiles and VMs correctly but then attempts a fresh install when changes are applied. I think cfops should not remove this file by default. Instead a --force or similar flag could be used or simply a warning printed to the console to delete this file if you still run into problems.

Thank you,

**Comment by xchapter7x** [comment]
recent commit adds this functionality.
the user will need to explicitly add a `clear-bosh-manifest` flag

expect this to be in the next release (likely next week sometime)

**Comment by xchapter7x** [comment]
https://github.com/pivotalservices/cfops/releases/tag/v2.1.15
