### ISSUE TITLE
Get error "opsmanager_builder.go:22] Can't find IaaS error: %!(EXTRA <nil>)" when backup 

### ISSUE THREAD

**Issue by devtdeng** [pivotalservices/cfops#65]
Ops Manager v1.6.9
ER v1.6.17
cfops v2.1.7

When executing `cfops backup --omh <ops manager IP> --du admin --dp <password> --omu ubuntu --omp <password> -d . -t ops-manager`, 

failed with error

```
2016/03/24 08:18:42 I0324 08:18:42.428381 3889 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/03/24 08:18:43 E0324 08:18:43.175942 3889 opsmanager_builder.go:22] Can't find IaaS error: %!(EXTRA <nil>)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x617786]

goroutine 1 [running]:
panic(0x999ee0, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/pivotalservices/gtils/command.(*DefaultRemoteExecutor).Execute(0xc82001a630, 0x7f6b9a1961c0, 0xc82002c068, 0xb262c0, 0x38, 0x0, 0x0)
	/go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/gtils/command/remote_execute.go:94 +0x86
github.com/pivotalservices/cfbackup/tiles/opsmanager.(*OpsManager).saveDeployments(0xc82017e480, 0x0, 0x0)
	/go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:97 +0x292
github.com/pivotalservices/cfbackup/tiles/opsmanager.(*OpsManager).Backup(0xc82017e480, 0x0, 0x0)
	/go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:86 +0x2f
main.runTileAction(0xa561f0, 0x6, 0x7f6b9a1d7c78, 0xc82017e480, 0x0, 0x0)
	/go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:67 +0x1ce
main.buraAction.func1(0xc82017e240)
	/go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:42 +0x9a6
github.com/codegangsta/cli.Command.Run(0xa561f0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb06200, 0x2b, 0xc8201800a0, ...)
	/go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0x1081
github.com/codegangsta/cli.(*App).Run(0xc82017e000, 0xc820082000, 0x10, 0x10, 0x0, 0x0)
	/go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:176 +0xffa
main.main()
	/go/src/github.com/pivotalservices/cfops/cmd/cfops/main.go:26 +0x6f
```

**Comment by datianshi** [comment]
@devtdeng 
which IAAS this is? 
Can you run this with debug enabled? LOG_LEVEL=debug
Last, can you provide the installation_settings?

**Comment by manaspatkar21** [comment]
Even I experienced a similar issue. We have installed Pivotal on VSphere

**Comment by manaspatkar21** [comment]
We recently upgraded Pivotal Cloud Foundry to Ops MAnager 1.6.11 and Elastic Runtime 1.6.17.

We started seeing the same error as mentioned above while running cfops backup for "ops-manager" tile.

**Comment by malston** [comment]
I believe the issue occurs when there is a ! in the ubuntu user's password.

On Friday, March 25, 2016, manaspatkar21 <notifications@github.com> wrote:

> We recently upgraded Pivotal Cloud Foundry to Ops MAnager 1.6.11 and
> Elastic Runtime 1.6.17.
>
> We started seeing the same error as mentioned above while running cfops
> backup for "ops-manager" tile.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotalservices/cfops/issues/65#issuecomment-201440768>
>


-- 
Sent from Gmail Mobile

**Comment by schabiyo** [comment]
@manaspatkar21 I currently have the exact setup and never experienced that issue. Are you also using version cfops 2.17?

**Comment by datianshi** [comment]
@manaspatkar21 

This error (Can't find IaaS error:) will happen with non ssh key authentication based environment (vSphere VMs using username and password )which is a little misleading. We will make a fix soon to display error appropriately, while now you can ignore the error as long as the backup proceeds.

The panic (panic: runtime error: invalid memory address or nil pointer dereference) though probably happen when cfops can not connect to the ops manager VM through ssh.
So either check the username and password of ssh credential or network maybe help

**Comment by manaspatkar21** [comment]
As part of troubleshooting, I ran the command from the Ops Manager VM ,but still the same issue. Hence I do not believe network could be an issue

Also cfops backup works for elastic-runtime. This is only an issue with ops-mnager til.

**Comment by manaspatkar21** [comment]
I enabled debug logging. Please let m know if this helps to figure out the issue

2016/03/25 20:13:58 D0325 20:13:58.334945 20598 createCliCommand.go:75] checking registry for 'ops-manager' tile
2016/03/25 20:13:58 D0325 20:13:58.335064 20598 createCliCommand.go:78] found tile in registry
2016/03/25 20:13:58 D0325 20:13:58.335163 20598 createCliCommand.go:81] we have all required flags and a proper builder
2016/03/25 20:13:58 D0325 20:13:58.335304 20598 remote_execute.go:25] using password for authn
2016/03/25 20:13:58 D0325 20:13:58.335397 20598 opsmanager.go:74] Exporting url 'https://10.134.175.1/api/installation_settings'
2016/03/25 20:13:58 D0325 20:13:58.335445 20598 opsmanager.go:128] attempting to auth against%!(EXTRA string=https://10.134.175.1/api/installation_settings)
2016/03/25 20:13:58 D0325 20:13:58.335508 20598 opsmanager.go:169] aquiring your token from: %!(EXTRA *url.URL=https://10.134.175.1/api/installation_settings, string=https://10.134.175.1/api/installation_settings)
2016/03/25 20:13:58 I0325 20:13:58.361977 20598 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/03/25 20:13:58 D0325 20:13:58.891291 20598 opsmanager.go:158] called basic auth on legacy ops manager%!(EXTRA string=https://10.134.175.1/api/installation_settings, <nil>)
2016/03/25 20:13:58 E0325 20:13:58.898908 20598 opsmanager_builder.go:22] Can't find IaaS error: %!(EXTRA <nil>)
2016/03/25 20:13:58 D0325 20:13:58.899022 20598 createCliCommand.go:64] Running backup for tile: &{BackupContext:{TargetDir:/home/ubuntu IsS3:false StorageProvider:0xc8201526b0} Hostname:10.134.175.1 Username:admin Password:XXXXXXXXXXXXX TempestPassword: DbEncryptionKey: Executer:0xc8200ef0e0 LocalExecuter:0x544cb0 SettingsUploader:0x599cb0 AssetsUploader:0x599cb0 SettingsRequestor:0xd6fbf8 AssetsRequestor:0xd6fbf8 DeploymentDir:/home/ubuntu/opsmanager/deployments OpsmanagerBackupDir:opsmanager SSHPrivateKey: SSHUsername:ubuntu SSHPassword:JGeWJU SSHPort:22}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x617786]

goroutine 1 [running]:
panic(0x999ee0, 0xc8200100f0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/pivotalservices/gtils/command.(*DefaultRemoteExecutor).Execute(0xc8200ef0e0, 0x7f040dd8c1e8, 0xc820028108, 0xb262c0, 0x38, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/gtils/command/remote_execute.go:94 +0x86
github.com/pivotalservices/cfbackup/tiles/opsmanager.(*OpsManager).saveDeployments(0xc820158360, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:97 +0x292
github.com/pivotalservices/cfbackup/tiles/opsmanager.(*OpsManager).Backup(0xc820158360, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:86 +0x2f
main.runTileAction(0xa561f0, 0x6, 0x7f040dd92be8, 0xc820158360, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:67 +0x1ce
main.buraAction.func1(0xc820158120)
        /go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:42 +0x9a6
github.com/codegangsta/cli.Command.Run(0xa561f0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb06200, 0x2b, 0xc82007f5e0, ...)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0x1081
github.com/codegangsta/cli.(*App).Run(0xc8200dfe60, 0xc82000a100, 0x10, 0x10, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:176 +0xffa
main.main()
        /go/src/github.com/pivotalservices/cfops/cmd/cfops/main.go:26 +0x6fF

**Comment by manaspatkar21** [comment]
2016/03/25 20:13:58 D0325 20:13:58.334945 20598 createCliCommand.go:75] checking registry for 'ops-manager' tile
2016/03/25 20:13:58 D0325 20:13:58.335064 20598 createCliCommand.go:78] found tile in registry
2016/03/25 20:13:58 D0325 20:13:58.335163 20598 createCliCommand.go:81] we have all required flags and a proper builder
2016/03/25 20:13:58 D0325 20:13:58.335304 20598 remote_execute.go:25] using password for authn
2016/03/25 20:13:58 D0325 20:13:58.335397 20598 opsmanager.go:74] Exporting url 'https://OPSMANAGERHOST/api/installation_settings'
2016/03/25 20:13:58 D0325 20:13:58.335445 20598 opsmanager.go:128] attempting to auth against%!(EXTRA string=https://OPSMANAGERHOST/api/installation_settings)
2016/03/25 20:13:58 D0325 20:13:58.335508 20598 opsmanager.go:169] aquiring your token from: %!(EXTRA *url.URL=https://OPSMANAGERHOST/api/installation_settings, string=https://OPSMANAGERHOST/api/installation_settings)
2016/03/25 20:13:58 I0325 20:13:58.361977 20598 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/03/25 20:13:58 D0325 20:13:58.891291 20598 opsmanager.go:158] called basic auth on legacy ops manager%!(EXTRA string=https://OPSMANAGERHOST/api/installation_settings, <nil>)
2016/03/25 20:13:58 E0325 20:13:58.898908 20598 opsmanager_builder.go:22] Can't find IaaS error: %!(EXTRA <nil>)
2016/03/25 20:13:58 D0325 20:13:58.899022 20598 createCliCommand.go:64] Running backup for tile: &{BackupContext:{TargetDir:/home/ubuntu IsS3:false StorageProvider:0xc8201526b0} Hostname:OPSMANAGERHOST Username:admin Password:XXXXXXXXXXXXX TempestPassword: DbEncryptionKey: Executer:0xc8200ef0e0 LocalExecuter:0x544cb0 SettingsUploader:0x599cb0 AssetsUploader:0x599cb0 SettingsRequestor:0xd6fbf8 AssetsRequestor:0xd6fbf8 DeploymentDir:/home/ubuntu/opsmanager/deployments OpsmanagerBackupDir:opsmanager SSHPrivateKey: SSHUsername:ubuntu SSHPassword:UBUNTUPASSWORD SSHPort:22}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x617786]

goroutine 1 [running]:
panic(0x999ee0, 0xc8200100f0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/pivotalservices/gtils/command.(*DefaultRemoteExecutor).Execute(0xc8200ef0e0, 0x7f040dd8c1e8, 0xc820028108, 0xb262c0, 0x38, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/gtils/command/remote_execute.go:94 +0x86
github.com/pivotalservices/cfbackup/tiles/opsmanager.(*OpsManager).saveDeployments(0xc820158360, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:97 +0x292
github.com/pivotalservices/cfbackup/tiles/opsmanager.(*OpsManager).Backup(0xc820158360, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/pivotalservices/cfbackup/tiles/opsmanager/opsmanager.go:86 +0x2f
main.runTileAction(0xa561f0, 0x6, 0x7f040dd92be8, 0xc820158360, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:67 +0x1ce
main.buraAction.func1(0xc820158120)
        /go/src/github.com/pivotalservices/cfops/cmd/cfops/createCliCommand.go:42 +0x9a6
github.com/codegangsta/cli.Command.Run(0xa561f0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb06200, 0x2b, 0xc82007f5e0, ...)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0x1081
github.com/codegangsta/cli.(*App).Run(0xc8200dfe60, 0xc82000a100, 0x10, 0x10, 0x0, 0x0)
        /go/src/github.com/pivotalservices/cfops/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:176 +0xffa
main.main()
        /go/src/github.com/pivotalservices/cfops/cmd/cfops/main.go:26 +0x6fF


The only thing I see is SSHPassword has a special character, which I don't see in the above logs. Does cfops accepts special character in Ops Manager VM password ?

**Comment by datianshi** [comment]
@manaspatkar21 
We just made a fix on better showing ssh connection error, which will be released later this week. https://github.com/pivotalservices/cfops/commit/161f11f1599fd7e283d6453c9d529a010dd2adc9

cfops does not parse password, so still recommend to check the password credential. 
Maybe using "[password]" incase the shell/scripts trailing password

**Comment by madhuchiluka** [comment]
OpsManager 1.6.12
cfops 2.1.

getting "falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)"
but backed up only nfs_server and MySQL data.

 cfops backup --omh 10.105.38.83 --du scpadmin --dp <> --omu ubuntu --omp <> -d SB4test1 -t elastic-runtime
2016/03/28 13:45:33 I0328 13:45:33.289003 30585 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/03/28 13:45:44 I0328 13:45:44.442945 30585 elasticruntime.go:138] Exporting nfs_server
2016/03/28 13:48:28 I0328 13:48:28.557581 30585 elasticruntime.go:138] Exporting mysql
$ 

Password is just letters. any idea?

**Comment by datianshi** [comment]
@manaspatkar21 You resolved the issue with ops manager backup? I saw your latest issue is about elastic runtime backup?...

**Comment by madhuchiluka** [comment]
No, I'm still getting "Can't find IaaS error"

2016/03/28 14:09:55 I0328 14:09:55.395316 1060 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/03/28 14:09:55 E0328 14:09:55.901733 1060 opsmanager_builder.go:22] Can't find IaaS error: %!(EXTRA <nil>)
2016/03/28 14:09:56 I0328 14:09:56.899434 1060 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/03/28 14:09:57 I0328 14:09:57.357329 1060 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)

**Comment by madhuchiluka** [comment]
IaaS is vSphere in our env

**Comment by datianshi** [comment]
@manaspatkar21 as I mentioned above  **"Can't find IaaS error"** is a  misleading error, which does not affect functionality of backing up vSphere ops manager

The issue from original author is backing up **ops manager tile**. And the **panic** from our analysis is when the ssh dial failed. 

Your error happens when backing up **elastic runtime tile**, which is a different issue. Can you open another issue, so we could analyze and bug tracking it?

Thank you

**Comment by madhuchiluka** [comment]
OK, I just opened another one for ert
https://github.com/pivotalservices/cfops/issues/67

**Comment by xchapter7x** [comment]
https://github.com/pivotalservices/cfops/releases/tag/v2.1.15
