### ISSUE TITLE
Getting error "falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)" during elastic runtime backup

### ISSUE THREAD

**Issue by madhuchiluka** [pivotalservices/cfops#67]
OpsManager 1.6.12
 cfops 2.1.7

getting "falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)"
 but backed up only nfs_server and MySQL data.

cfops backup --omh 10.105.38.83 --du scpadmin --dp <> --omu ubuntu --omp <> -d SB4test1 -t elastic-runtime
 2016/03/28 13:45:33 I0328 13:45:33.289003 30585 opsmanager.go:131] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
 2016/03/28 13:45:44 I0328 13:45:44.442945 30585 elasticruntime.go:138] Exporting nfs_server
 2016/03/28 13:48:28 I0328 13:48:28.557581 30585 elasticruntime.go:138] Exporting mysql
 $ 

Password contains just letters(removed special characters ). any idea?

**Comment by datianshi** [comment]
@madhuchiluka  what is the issue?

The backup of elastic runtime is to backup the blobstore, which is nfs_server, as well as the databases.

If you want to backup information of ops manager, you would specify **-t opsmanager** instead of -t elastic-runtime. 

If you want to backup them in onetime, specify **-tl 'opsmanager,er'**

**Comment by madhuchiluka** [comment]
Right.it is backing up only blobstore and mysql but not other databases for ex, uaadb.backup, ccdb.backup..etc. I only saw 2 files in the backup directory which are nfs_server and MySQL.

**Comment by xchapter7x** [comment]
Ops manager 1.6 no longer uses postgres by default. All of your persistence
(ccdb, consoles, uaadb,etc) will be in the mysql backup, if you have my SQL
selected as your persistence in ops manager.

**Comment by madhuchiluka** [comment]
Ahh, I thought we're using both MySQL and Postgres. but I just confirmed we have selected internal databases-MQSQL.

**Comment by madhuchiluka** [comment]
It looks like backing up both opsmanager and ert at a time is not working in 2.1.7 version. can you confirm this? 
I tried as -t 'ops-manager,elastic-runtime' 
getting error "2016/03/28 14:58:54 E0328 14:58:54.541636 8091 createCliCommand.go:48] there was an error getting tile from registry: invalid tile selected. try the 'list-tiles' option to see a list of available tiles"

**Comment by madhuchiluka** [comment]
$ cfops list-tiles
Available Tiles:
ops-manager
elastic-runtime

**Comment by datianshi** [comment]
@madhuchiluka 

@madhuchiluka  Yes. This is changed since cfops 2.x @xchapter7x 





[](url)

**Comment by xchapter7x** [comment]
that is correct.
as of version 2+ you need to execute a single backup/restore at a time.

2016-03-28 15:01 GMT-04:00 madhuchiluka <notifications@github.com>:
