### ISSUE TITLE
Docs / highlight that there is no need to have BOSH CLI

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotalservices/cfops#68]
I suggest to improve the doc / readme.
cfops does not relies on calling BOSH CLI (and Ruby that BOSH CLI needs) as it is calling BOSH director REST API directly.
This makes it nice to install in a techops VM that relies on some datastore that has also infrastructure driven snapshoting for example - as then backup created by cfops in such a techops VM gets automatically snapshotted.

This is different from the default Pivotal Cloud Foundry that describes use of BOSH CLI for some of the backup/restore tasks.
Of course BOSH CLI might be useful to manage Pivotal Cloud Foundry but one has BOSH CLI in Pivotal OpsManager already.

**Comment by xchapter7x** [comment]
thanks for the suggestion. just added:
https://github.com/pivotalservices/cfops/commit/6761f0381d9d71e249b1bf81e4eb43ff3b5b7680

**Comment by avasseur-pivotal** [comment]
I would really suggest to explicitly write "BOSH CLI is not needed as cfops interacts with BOSH director thru the REST endpoints directly". That makes it more explicit imho
