### ISSUE TITLE
Plugins failing with RabbitMQ tile installed in Ops Manager

### ISSUE THREAD

**Issue by jtgammon** [pivotalservices/cfops#74]
I have a reproducible issue where both the helloworld and mysql plugins fail when the RabbitMQ tile is installed in Ops Manager. When the tile is removed both plugins work. This only effects plugins and does not effect ops-manager or elastic-runtime.

The error is EOF when it fails:
2016/04/05 17:43:27 E0405 17:43:27.639842 7058 createCliCommand.go:45] there was an error: unexpected EOF running backup on helloworld tile:&{0xc82033b560}

**Comment by xchapter7x** [comment]
John wasn't there another error referring to a un-registered gob type?

**Comment by jtgammon** [comment]
Yes, attaching the full debug log.

[pcf-lab-2016-04-05_14.41.10.log.zip](https://github.com/pivotalservices/cfops/files/205425/pcf-lab-2016-04-05_14.41.10.log.zip)

**Comment by xchapter7x** [comment]
this should now be resolved
https://github.com/pivotalservices/cfops/releases/tag/v2.2.4
