### ISSUE TITLE
cfops v2.2.4 does not backup mysql tile in ubuntu; MacOS version works fine.

### ISSUE THREAD

**Issue by rsamban** [pivotalservices/cfops#76]
cfops v2.2.4 does not backup mysql tile in ubuntu; MacOS version works fine.
Following is the error message

ecs@UbuntuUtility:~/cf-ops$ ./cfops backup --omh <OPS_MGR_HOST> --du admin --dp <PWD> --omu ubuntu --omp <OS_PWD> -d ./backup --tile mysql-tile
2016/04/11 13:13:18 I0411 13:13:18.479747 4813 opsmanager.go:132] falling back to basic auth for legacy system%!(EXTRA *errors.errorString=)
2016/04/11 13:13:19 Plugin address: unix /tmp/plugin225498756
2016/04/11 13:13:19 E0411 13:13:19.062986 4813 createCliCommand.go:45] there was an error: Product not found p-mysql running backup on mysql-tile tile:&{0xc820016f60}
NAME:
   cfops backup - creates a backup archive of the target tile

USAGE:
   cfops backup [command options] [arguments...]

DESCRIPTION:
   backup --opsmanagerhost <host> --adminuser <usr> --adminpass <pass> --opsmanageruser <opsuser> --opsmanagerpass <opspass> -d <dir> --tile elastic-runtime

OPTIONS:
   --opsmanagerhost, --omh 	hostname for Ops Manager [$CFOPS_HOST]
   --adminuser, --du 		username for Ops Mgr admin (Ops Manager WebConsole Credentials) [$CFOPS_ADMIN_USER]
   --opsmanagerpass, --omp 	password for Ops Manager VM Access (used for ssh connections) [$CFOPS_OM_PASS]
   --clear-bosh-manifest 	set this flag if you would like to clear the bosh-deployments.yml (this should only affect a restore of Ops-Manager) [$CFOPS_CLEAR_BOSH_MANIFEST]
   --pluginargs, -p 		Arguments for plugin to execute [$CFOPS_PLUGIN_ARGS]
   --adminpass, --dp 		password for Ops Mgr admin (Ops Manager WebConsole Credentials) [$CFOPS_ADMIN_PASS]
   --opsmanageruser, --omu 	username for Ops Manager VM Access (used for ssh connections) [$CFOPS_OM_USER]
   --destination, -d 		path of the Cloud Foundry archive [$CFOPS_DEST_PATH]
   --tile, -t 			a tile you would like to run the operation on [$CFOPS_TILE]
   --encryptionkey, -k 		encryption key to encrypt/decrypt your archive (key lengths supported are 16, 24, 32 for AES-128, AES-192, or AES-256) [$CFOPS_ENCRYPTION_KEY]

**Comment by calebwashburn** [comment]
This is an issue we are working to recover.  Should work if you use v0.0.15 of plugin as v0.0.16/v0.0.17 have a defect and have been pulled back from releases.  https://pivotal-cfops.s3.amazonaws.com/mysql-plugin-release/linux64/v0.0.15/cfops-mysql-plugin

**Comment by calebwashburn** [comment]
@rsamban Has this been resolved with latest version of mysql-plugin and cfops?

**Comment by rsamban** [comment]
yes, it did.

thanks
-Ramesh
