### ISSUE TITLE
1.7 backups require uaa admin user on ops manager to have scopes added

### ISSUE THREAD

**Issue by xchapter7x** [pivotalservices/cfops#86]
1.7 backups require uaa admin user on ops manager to have scopes added

must add:
`opsman.admin` or `opsman.user`

**Comment by cloudmadch** [comment]
Hi,


cfops v2.1.7
ERT 1.7.3
opsmanager 1.7.4

I have verified my admin user has both opsman.admin and opsman.user scopes. but still getting following error when I run cfops backup tool

2016/06/22 16:11:29 E0622 16:11:29.683384 2095 opsmanager.go:145] error in save http request%!(EXTRA *errors.errorString={"error":"Your UAA access token has expired and Your UAA access token does not have either \"opsman.admin\" or \"opsman.user\" scope"})
2016/06/22 16:11:29 E0622 16:11:29.683442 2095 createCliCommand.go:48] there was an error getting tile from registry: failure to connect to ops manager host: {"error":"Your UAA access token has expired and Your UAA access token does not have either \"opsman.admin\" or \"opsman.user\" scope"}
NAME:


Thanks, M

**Comment by xchapter7x** [comment]
The version of cfops you are using does not support the 1.7 uaa changes in
PCF.
please upgrade to the latest cfops release from
http://www.cfops.io/downloads/release/ (v2.2.x)

-John

2016-06-22 16:16 GMT-04:00 cloudmadch <notifications@github.com>:

**Comment by cloudmadch** [comment]
I just upgraded to latest v2.2.29. getting same error 

I'm running as below

cfops backup --omh 10.x.x.x --dp xxxxxx --omp xxxxxx -t elastic-runtime --du admin --omu ubuntu -d SB4test

and, admin user has required scopes. Did I miss anything here?

**Comment by xchapter7x** [comment]
the `omh` flag must be the domain you created the ops manager with.
otherwise the uaa will not allow the connection.
Also, does your ops manager have saml or ldap configured?

-John

2016-06-22 16:45 GMT-04:00 cloudmadch <notifications@github.com>:

**Comment by cloudmadch** [comment]
Ahh okay, it started exporting database now after I gave full dns name. 

No, we haven't configured saml or ldap yet but we are planning to. but only one user can login at a time to webUI. have you guys tested out with AD users?

Thanks, M

**Comment by Murryy79** [comment]
@xchapter7x  i am using the full domain name for --omh but still getting this error.
cfops version:  v3.0.4
OpsMan version 1.9

any help with cfops is appreciated.

**Comment by henryaj** [comment]
Hi @Murryy79,

It may be worth using `uaac-cli` to see if your client ID/secret are usable - you can do this by following the instructions at http://www.cfops.io/#authentication-connection-errors.

If you're still having trouble, we'd recommended opening a support ticket with [Pivotal Support](support.pivotal.io).

Thanks,

Henry
