### ISSUE TITLE
cfops elastic-runtime backup of PCF 1.7 postgres DBs exit rc 127 empty files

### ISSUE THREAD

**Issue by rguilme1** [pivotalservices/cfops#90]
I tested the PCF 1.7 elastic-runtime tile backup using v2.2.20.  The backup says it works, but the output files are empty.  I ran with debug and the process exits with rc 127.

In ERT 1.7 the postgres package location has changed to /var/vcap/packages/postgres-9.4.6.  The debug log shows:

2016/06/02 05:04:32 I0602 05:04:32.160216 27248 elasticruntime.go:138] Exporting %s ccdb
2016/06/02 05:04:32 D0602 05:04:32.229796 27248 pgdump.go:70] pgdump Dump called:  PGPASSWORD=030df4fe78359255 /var/vcap/packages/postgres-9.4.2/bin/pg_dump -Fc -h localhost -U vcap -p 2544 ccdb Process exited with status 127
2016/06/02 05:04:32 D0602 05:04:32.230644 27248 elasticruntime.go:143] Done backing up %s ccdb

postgres-9.4.2 is not there.

Please update the postgres path to use postgres-9.4.6 when dumping ERT 1.7.

Thank you
  - Rick

**Comment by xchapter7x** [comment]
this should be fixed in the latest release (2.2.21+)
http://www.cfops.io/downloads/release/

via: https://github.com/pivotalservices/cfbackup/commit/24227a9766d0e43b8bc43e80678dadd9c69991c7
